import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-theme-background ${geistMono.variable}`}>
      <body className="antialiased font-mono overflow-x-hidden min-h-screen leading-loose text-theme-text">
        <main className="relative container mx-auto max-w-prose min-h-screen overflow-y-clip py-16 px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
